#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

set -e

runApplication blockMesh
runApplication checkMesh

runApplication decomposePar -force
runParallel simpleFoam
runApplication reconstructPar -latestTime
rm -rf processor*
postProcess -func writeCellCentres
python3 residualPlot.py
