#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

set -e

runApplication blockMesh

runApplication checkMesh

# Now decompose the snappy mesh for the solver
runApplication decomposePar -force

# Run the solver
runParallel $(getApplication)
#mpirun --use-hwthread-cpus -np 96 simpleFoam -parallel

# Reconstruct results
runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

rm -rf processor*

python3 residualPlot.py
